<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:arg name="prepend_prefix_to_laser_frame" default="false" />
  
  <xacro:include filename="$(find sw200_description)/urdf/include/common_properties.urdf.xacro" />
  <xacro:include filename="$(find sw200_description)/urdf/include/imu.gazebo.urdf.xacro" />
  <xacro:include filename="$(find sw200_description)/urdf/include/sw200.gazebo.xacro" />
  <xacro:include filename="$(find sw200_description)/urdf/include/sw200.transmission.xacro" />
  <xacro:include filename="$(find sw200_description)/urdf/include/sick_551.urdf.xacro" />
  <xacro:include filename="$(find sw200_description)/urdf/include/_d435.urdf.xacro" />
  <xacro:include filename="$(find sw200_description)/urdf/include/urm04_sensor.xacro" />

  <xacro:property name="deg_to_rad" value="0.017453293" />

    <xacro:property name="sw200_base_mass" value="40" />

  <xacro:property name="sw200_act_wheel_radius" value="0.09" />
  <xacro:property name="sw200_act_wheel_width" value="0.032" />
  <xacro:property name="sw200_act_wheel_mass" value="0.9" />
  <xacro:property name="sw200_act_wheel_dx" value="0" />
  <xacro:property name="sw200_act_wheel_dy" value="0.272604" />

  <xacro:property name="sw200_caster_wheel_radius" value="0.0625" />
  <xacro:property name="sw200_caster_wheel_width" value="${sw200_act_wheel_width}" />
  <xacro:property name="sw200_caster_wheel_mass" value="${sw200_act_wheel_mass}" />
  <xacro:property name="sw200_caster_wheel_dx" value="-0.0382" />
  <xacro:property name="sw200_caster_wheel_dy" value="0" />
  <xacro:property name="sw200_caster_wheel_dz" value="-0.099" />
  <xacro:property name="sw200_front_caster_wheel_base_dx" value="0.341346" />
  <xacro:property name="sw200_back_caster_wheel_base_dx" value="-0.30" />
  <xacro:property name="sw200_caster_wheel_base_dy" value="0.25" />
  <xacro:property name="sw200_caster_wheel_base_dz" value="${sw200_caster_wheel_radius-sw200_caster_wheel_dz}" />

  <xacro:property name="imu_stdev" value="0.00017" />

  <xacro:macro name="actuated_wheel" params="prefix locationprefix locationright">
    <joint name="${prefix}${locationprefix}_wheel_joint" type="continuous">
      <origin xyz="0.0 ${-sw200_act_wheel_dy * locationright} ${sw200_act_wheel_radius}" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}${locationprefix}_wheel_link" />
      <axis xyz="0 1 0" />
      <limit effort="100" velocity="20.0" />
    </joint>

    <link name="${prefix}${locationprefix}_wheel_link">
      <xacro:cylinder_inertial mass="${sw200_act_wheel_mass}" radius="${sw200_act_wheel_radius}" length="${sw200_act_wheel_width}">
        <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
      </xacro:cylinder_inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://sw200_description/meshes/visual/wheel1.STL" />
        </geometry>
        <xacro:insert_block name="material_dark_grey" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://sw200_description/meshes/visual/wheel1.STL" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}${locationprefix}_wheel_link">
      <material>Gazebo/DarkGrey</material>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="caster_wheel" params="prefix locationprefix locationright wheel_base_dx">
    <!-- caster hub -->
    <joint name="${prefix}${locationprefix}_caster_rotation_joint" type="continuous">
      <origin xyz="${wheel_base_dx} ${-sw200_caster_wheel_base_dy * locationright} ${sw200_caster_wheel_base_dz}" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}${locationprefix}_caster_rotation_link" />
      <axis xyz="0 0 1" />
      <dynamics damping="0.01" friction="0.0"/>
    </joint>

    <link name="${prefix}${locationprefix}_caster_rotation_link">
      <inertial>
        <!-- <origin xyz="0 0 -0.042500000044" rpy="${0.5 * pi} ${24 * deg_to_rad} ${1.5 * pi}" /> -->
        <origin xyz="0 0 -0.042500000044" rpy="${24 * deg_to_rad} 0 ${0.5 * pi} " />
        <mass value="0.3097539019" />
        <inertia
          ixx="0.0005844517978"
          ixy="0"
          ixz="0"
          iyy="0.00052872551237"
          iyz="0"
          izz="0.00017923555074" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://sw200_description/meshes/visual/caster_wheel_base.stl" />
        </geometry>
        <xacro:insert_block name="material_silver" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://sw200_description/meshes/collision/caster_wheel_base.stl" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}${locationprefix}_caster_rotation_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <!-- caster wheel -->
    <joint name="${prefix}${locationprefix}_caster_wheel_joint" type="continuous">
      <origin xyz="${sw200_caster_wheel_dx} ${-sw200_caster_wheel_dy * locationright} ${sw200_caster_wheel_dz}" rpy="0 0 0" />
      <parent link="${prefix}${locationprefix}_caster_rotation_link" />
      <child link="${prefix}${locationprefix}_caster_wheel_link" />
      <axis xyz="0 1 0" />
    </joint>

    <link name="${prefix}${locationprefix}_caster_wheel_link">
      <xacro:cylinder_inertial mass="${sw200_caster_wheel_mass}" radius="${sw200_caster_wheel_radius}" length="${sw200_caster_wheel_width}">
        <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
      </xacro:cylinder_inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://sw200_description/meshes/visual/wheel.stl" />
        </geometry>
        <xacro:insert_block name="material_dark_grey" />
        
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://sw200_description/meshes/visual/wheel.stl" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}${locationprefix}_caster_wheel_link">
      <material>Gazebo/DarkGrey</material>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="sw200" params="prefix">
    <link name="${prefix}base_footprint" />

    <joint name="${prefix}base_joint" type="fixed">
      <parent link="${prefix}base_footprint" />
      <child link="${prefix}base_link" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="${prefix}base_link">
      <xacro:box_inertial mass="${sw200_base_mass}" x="0.986" y="0.636" z="0.220">
        <origin xyz="${sw200_act_wheel_dx} 0 0.03180" rpy="0 0 0" />
      </xacro:box_inertial>
      <visual>
        <origin xyz="0.11350 -0.77931 -0.51677" rpy="1.5707 0 3.14159" />
        <geometry>
          <!--mesh filename="package://sw200_description/meshes/visual/sw200_100_base.stl" /-->
          <mesh filename="package://sw200_description/meshes/visual/robot_3.STL" />
        </geometry>
        <xacro:insert_block name="material_white" />
      </visual>
      <collision>
        <origin xyz="0.11350 -0.77931 -0.51677" rpy="1.5707 0 3.14159" />
        <geometry>
        <!--mesh filename="package://sw200_description/meshes/visual/sw200_100_base.stl" /-->
          <mesh filename="package://sw200_description/meshes/collision/robot_3.STL" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}base_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <!-- IMU -->
    <joint name="${prefix}base_link_to_imu_joint" type="fixed">
      <parent link="${prefix}base_link" />
      <child link="${prefix}imu_link" />
      <origin xyz="0.0 0.0 0.25" rpy="0 0 0" />  <!-- same as real sw200 -->
    </joint>

    <link name="${prefix}imu_link" />

    <xacro:imu_gazebo link="${prefix}imu_link" imu_topic="imu_data" update_rate="50.0" stdev="${imu_stdev}" />

    <!-- Create an alias for imu_link. This is necessary because the real sw200's
         TF has imu_link, but the imu_data topic is published in the imu_frame
         frame. -->
    <joint name="${prefix}imu_link_to_imu_frame_joint" type="fixed">
      <parent link="${prefix}imu_link" />
      <child link="${prefix}imu_frame" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="${prefix}imu_frame" />

    <!-- camera -->
  <xacro:arg name="use_nominal_extrinsics" default="True" />
  

  <xacro:sensor_d435 parent="${prefix}base_link" name="camera_top">
    <origin xyz="0.46 0 0.13" rpy="0 0 0"/>
    
  </xacro:sensor_d435>

       <gazebo reference="camera_top">
      <material>Gazebo/Grey</material>
    </gazebo>

    <!-- Laser scanners -->
    <joint name="${prefix}base_link_to_front_laser_joint" type="fixed">
      <parent link="${prefix}base_link" />
      <child link="${prefix}front_laser_link" />
      <origin xyz="0.35 0.0 0.21" rpy="0.0 3.14 3.14" />  <!-- from visually matching up the meshes of the sw200 and the laser scanner -->
    </joint>
    <xacro:sick_551 prefix="${prefix}" link="front_laser_link" topic="f_scan"
                     prepend_prefix_to_laser_frame="$(arg prepend_prefix_to_laser_frame)" />

    <!-- Ultrasound sensors  top-->

  <xacro:urm04_sensor frame_name="left_sensor" ros_topic="left_sensor" update_rate="10" min_range="0.04" max_range="0.1" horizontal_field_of_view="1.04" vertical_field_of_view="0.04" ray_count="2" />
  <link name="left_sensor">
    <visual>
      <origin xyz="0 0 0" rpy="1.5707 0 0" />
      <geometry>
        <mesh filename="package://sw200_description/meshes/visual/urm04.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="black" />
    </visual>
  </link>
    <joint name="left_sensor_joint" type="fixed">
    <origin xyz="0.48 0.21 0.16139" rpy="0 0 0" />
    <parent link="${prefix}base_link"/>
    <child link="left_sensor" />
  </joint>


   <xacro:urm04_sensor frame_name="right_sensor" ros_topic="right_sensor" update_rate="10" min_range="0.04" max_range="0.1" horizontal_field_of_view="1.04" vertical_field_of_view="0.04" ray_count="2" />
  <link name="right_sensor">
    <visual>
      <origin xyz="0 0 0" rpy="1.5707 0 0" />
      <geometry>
        <mesh filename="package://sw200_description/meshes/visual/urm04.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="black" />
    </visual>
  </link>
    <joint name="right_sensor_joint" type="fixed">
    <origin xyz="0.48 -0.21 0.16139" rpy="0 0 0" />
    <parent link="${prefix}base_link"/>
    <child link="right_sensor" />
  </joint>
    <!-- Ultrasound sensors  botton-->

  <xacro:urm04_sensor frame_name="front_sensor" ros_topic="front_sensor" update_rate="10" min_range="0.04" max_range="0.1" horizontal_field_of_view="1.04" vertical_field_of_view="0.04" ray_count="2" />
  <link name="front_sensor">
    <visual>
      <origin xyz="0 0 0" rpy="1.5707 0 0" />
      <geometry>
        <mesh filename="package://sw200_description/meshes/visual/urm04.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="black" />
    </visual>
  </link>
    <joint name="front_sensor" type="fixed">
    <origin xyz="-0.49 0.21 0.16139" rpy="0 0 -3.14" />
    <parent link="${prefix}base_link"/>
    <child link="front_sensor" />
  </joint>


   <xacro:urm04_sensor frame_name="rear_sensor" ros_topic="rear_sensor" update_rate="10" min_range="0.04" max_range="0.1" horizontal_field_of_view="1.04" vertical_field_of_view="0.04" ray_count="2" />
  <link name="rear_sensor">
    <visual>
      <origin xyz="0 0 0" rpy="1.5707 0 0" />
      <geometry>
        <mesh filename="package://sw200_description/meshes/visual/urm04.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="black" />
    </visual>
  </link>
    <joint name="rear_sensor" type="fixed">
    <origin xyz="-0.49 -0.21 0.16139" rpy="0 0 -3.14" />
    <parent link="${prefix}base_link"/>
    <child link="rear_sensor" />
  </joint>
   
    
  

    <!-- wheels -->
    <xacro:actuated_wheel prefix="${prefix}" locationprefix="left" locationright="-1"/>
    <xacro:actuated_wheel prefix="${prefix}" locationprefix="right" locationright="1"/>
    <xacro:caster_wheel prefix="${prefix}" locationprefix="fl" locationright="-1" wheel_base_dx="${sw200_front_caster_wheel_base_dx}"/>
    <xacro:caster_wheel prefix="${prefix}" locationprefix="fr" locationright="1" wheel_base_dx="${sw200_front_caster_wheel_base_dx}"/>
    <xacro:caster_wheel prefix="${prefix}" locationprefix="bl" locationright="-1" wheel_base_dx="${sw200_back_caster_wheel_base_dx}"/>
    <xacro:caster_wheel prefix="${prefix}" locationprefix="br" locationright="1" wheel_base_dx="${sw200_back_caster_wheel_base_dx}"/>

    <joint name="${prefix}base_link_surface_joint" type="fixed">
      <origin xyz="${sw200_act_wheel_dx} 0 0.352" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}surface" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="${prefix}surface"/>

    <xacro:sw200_wheel_transmissions prefix="${prefix}"/>

    <!-- set the gazebo friction parameters for the wheels -->
    <xacro:set_all_wheel_frictions prefix="${prefix}"/>

    <p3d_base_controller prefix="${prefix}" />
  </xacro:macro>
</robot>